### ISSUE TITLE
__init__.py : NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by tnniras** [yorubadeveloper/flask-admin-boilerplate#3]
Hi Team,

During my initial clone, I have observed below error :

It seems we need to `import os` in __init__.py

```
(venv) tusharniras@tusharniras-macbookpro:~/Desktop/sanbox/flask-admin-boilerplate$ python app.py
Traceback (most recent call last):
  File "/Users/tusharniras/Desktop/sanbox/flask-admin-boilerplate/app.py", line 4, in <module>
    from views import *
  File "/Users/tusharniras/Desktop/sanbox/flask-admin-boilerplate/views/__init__.py", line 3, in <module>
    from model import *
  File "/Users/tusharniras/Desktop/sanbox/flask-admin-boilerplate/model/__init__.py", line 3, in <module>
    from helpers.database import *
  File "/Users/tusharniras/Desktop/sanbox/flask-admin-boilerplate/helpers/database.py", line 2, in <module>
    import configuration
  File "/Users/tusharniras/Desktop/sanbox/flask-admin-boilerplate/configuration/__init__.py", line 11, in <module>
    app.config['MAIL_PASSWORD'] = os.environ['MAIL_PASSWORD'] #password
NameError: name 'os' is not defined
(venv) tusharniras@tusharniras-macbookpro:~/Desktop/sanbox/flask-admin-boilerplate$ 
```

**Comment by tnniras** [comment]
requested the pull request
